version: '3'

services:
   nginx:
      image: nginx
      volumes:
         - ./nginx:/etc/nginx/conf.d
      ports:
         - "80:80"

   flask_app:
      image: gfi
      expose:
         - "8000"